/*
 * src/backends/bin_loader.c — LMc Custom Binary Format Loader
 *
 * Loads the LMc/GPT-2 custom float32 binary format (.bin).
 * Generated by: python3 converter.py
 *
 * File layout (little-endian):
 *   Header:
 *     [uint32 magic    ] = 0x47505432 ("GPT2")
 *     [uint32 version  ] = 1
 *     [uint32 vocab_size]
 *     [uint32 seq_len  ]
 *     [uint32 n_layers ]
 *     [uint32 n_heads  ]
 *     [uint32 embed_dim]
 *   Weight data:
 *     float32 arrays in the order defined by lmc_gpt2_assign_weight_ptrs()
 *
 * Notes:
 *   - Weights are stored in row-major [out, in] order (transposed from
 *     HuggingFace's Conv1D [in, out]).
 *   - GPT-2 uses tied weights: lm_head == wte.
 *
 * SPDX-License-Identifier: MIT
 */

#include "lmc_internal.h"

/* ============================================================
 * CONSTANTS
 * ============================================================ */
#define BIN_MAGIC   0x47505432U   /* "GPT2" as uint32 LE */
#define BIN_VERSION 1

/* ============================================================
 * HEADER READING HELPER
 * ============================================================ */
static LmcError read_u32(FILE *f, const char *path, uint32_t *out) {
    if (fread(out, sizeof(uint32_t), 1, f) != 1) {
        LMC_ERROR("Truncated header in: %s", path);
        return LMC_ERR_IO;
    }
    return LMC_OK;
}

/* ============================================================
 * LOAD .BIN MODEL
 * ============================================================ */
LmcError lmc_load_bin(LmcContext *ctx, const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        LMC_ERROR("Cannot open model file: %s", path);
        LMC_ERROR("Run: python3 scripts/converter.py  to generate it.");
        return LMC_ERR_IO;
    }

    LmcError err;
    uint32_t magic, version, vocab_size, seq_len, n_layers, n_heads, embed_dim;

#define RU32(var) \
    do { err = read_u32(f, path, &(var)); if (err != LMC_OK) { fclose(f); return err; } } while(0)

    RU32(magic);
    RU32(version);
    RU32(vocab_size);
    RU32(seq_len);
    RU32(n_layers);
    RU32(n_heads);
    RU32(embed_dim);
#undef RU32

    /* Validate magic */
    if (magic != BIN_MAGIC) {
        LMC_ERROR("Bad magic 0x%08X in %s (expected 0x%08X)", magic, path, BIN_MAGIC);
        fclose(f);
        return LMC_ERR_FORMAT;
    }

    if (version != BIN_VERSION) {
        LMC_ERROR("Version mismatch: file has v%u, expected v%u", version, BIN_VERSION);
        fclose(f);
        return LMC_ERR_FORMAT;
    }

    /* Validate architecture */
    if (vocab_size != GPT2_VOCAB_SIZE ||
        seq_len    != GPT2_SEQ_LEN    ||
        n_layers   != GPT2_N_LAYERS   ||
        n_heads    != GPT2_N_HEADS    ||
        embed_dim  != GPT2_EMBED_DIM) {
        LMC_ERROR("Architecture mismatch in %s:", path);
        LMC_ERROR("  Expected: V=%d S=%d L=%d H=%d D=%d",
                  GPT2_VOCAB_SIZE, GPT2_SEQ_LEN, GPT2_N_LAYERS,
                  GPT2_N_HEADS, GPT2_EMBED_DIM);
        LMC_ERROR("  File has: V=%u S=%u L=%u H=%u D=%u",
                  vocab_size, seq_len, n_layers, n_heads, embed_dim);
        fclose(f);
        return LMC_ERR_ARCH;
    }

    /* Allocate arena and assign weight pointers */
    size_t n_params = lmc_gpt2_param_count();
    LMC_INFO("Parameters   : %zu  (%.1f MB float32)",
             n_params, n_params * 4.0 / (1024*1024));

    err = lmc_arena_init(&ctx->arena, n_params);
    if (err != LMC_OK) { fclose(f); return err; }

    err = lmc_gpt2_assign_weight_ptrs(ctx);
    if (err != LMC_OK) { fclose(f); return err; }

    /* Read all weights in one shot */
    size_t n_read = fread(ctx->arena.data, sizeof(float), n_params, f);
    if (n_read != n_params) {
        LMC_ERROR("Truncated weight data in %s (read %zu / %zu floats)",
                  path, n_read, n_params);
        fclose(f);
        return LMC_ERR_IO;
    }

    /* Tied weights: lm_head = wte */
    ctx->weights.lm_head = ctx->weights.wte;

    fclose(f);
    LMC_INFO("Loaded       : %s (float32 .bin)", path);
    return LMC_OK;
}
